using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using report_service.Models;

namespace report_service.Services;

public class PdfService
{
    public byte[] Generate(ReportData data)
    {
        // QuestPDF community license is free for open-source and portfolio projects
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            // ── Page 1: Cover ────────────────────────────────────────────
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Content().Column(col =>
                {
                    col.Item().PaddingTop(80).Text("Fronius Solar.creator")
                        .FontSize(28).Bold().FontColor("#FF6600");

                    col.Item().PaddingTop(16).Text(data.ProjectName)
                        .FontSize(20).FontColor("#333333");

                    col.Item().PaddingTop(8).Text(data.ProjectDate)
                        .FontSize(12).FontColor("#666666");

                    col.Item().PaddingTop(40).Text("Prepared for:")
                        .FontSize(11).FontColor("#666666");

                    col.Item().Text($"{data.CustomerFirstName} {data.CustomerLastName}")
                        .FontSize(14).Bold();

                    if (data.CustomerCompany is not null)
                        col.Item().Text(data.CustomerCompany).FontSize(12);

                    col.Item().PaddingTop(80)
                        .Text("This report was generated by Fronius Solar.creator. " +
                              "All calculations are based on PVGIS irradiance data and " +
                              "standard system loss factors.")
                        .FontSize(9).FontColor("#999999").Italic();
                });
            });

            // ── Page 2: PV System Overview ───────────────────────────────
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("PV System Overview").FontSize(16).Bold().FontColor("#FF6600");

                page.Content().PaddingTop(20).Column(col =>
                {
                    // Key metrics table
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c => { c.RelativeColumn(); c.RelativeColumn(); });

                        AddMetricRow(table, "Solar Irradiance", $"{data.IrradianceKwhM2:N0} kWh/m²/year");
                        AddMetricRow(table, "PV Peak Power", $"{data.PeakPowerKwp:N2} kWp");
                        AddMetricRow(table, "Yearly Yield", $"{data.YearlyYieldKwh:N0} kWh");
                        AddMetricRow(table, "Performance Ratio", $"{data.PerformanceRatio * 100:N0}%");
                        AddMetricRow(table, "Self-Consumption", $"{data.SelfConsumptionRate * 100:N1}%");
                        AddMetricRow(table, "Self-Sufficiency", $"{data.SelfSufficiencyRate * 100:N1}%");
                    });

                    col.Item().PaddingTop(20).Text("Profitability").FontSize(14).Bold();

                    col.Item().PaddingTop(8).Table(table =>
                    {
                        table.ColumnsDefinition(c => { c.RelativeColumn(); c.RelativeColumn(); });

                        AddMetricRow(table, "Annual Savings", $"€ {data.SavingsPerYear:N0}");
                        AddMetricRow(table, "Feed-in Revenue", $"€ {data.FeedInRevenue:N0}");
                        AddMetricRow(table, "Return on Investment", $"{data.ReturnOnInvestmentMonths / 12:N1} years");
                        AddMetricRow(table, "CO₂ Savings", $"{data.Co2SavingsKgPerYear / 1000:N2} t/year");
                        AddMetricRow(table, "Total System Cost", $"€ {data.TotalSystemCostEur:N0}");
                    });
                });

                page.Footer().AlignRight()
                    .Text(x => { x.Span("Page "); x.CurrentPageNumber(); x.Span(" of "); x.TotalPages(); });
            });

            // ── Page 3: Annual Overview ──────────────────────────────────
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("Annual Production Overview").FontSize(16).Bold().FontColor("#FF6600");

                page.Content().PaddingTop(20).Column(col =>
                {
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.ConstantColumn(80);
                            c.RelativeColumn();
                            c.RelativeColumn();
                        });

                        table.Header(h =>
                        {
                            h.Cell().Text("Month").Bold();
                            h.Cell().Text("Production (kWh)").Bold();
                            h.Cell().Text("Consumption (kWh)").Bold();
                        });

                        var months = new[] { "Jan","Feb","Mar","Apr","May","Jun",
                                             "Jul","Aug","Sep","Oct","Nov","Dec" };

                        foreach (var m in data.MonthlyData)
                        {
                            table.Cell().Text(months[m.Month - 1]);
                            table.Cell().Text($"{m.ProductionKwh:N0}");
                            table.Cell().Text($"{m.ConsumptionKwh:N0}");
                        }
                    });
                });

                page.Footer().AlignRight()
                    .Text(x => { x.Span("Page "); x.CurrentPageNumber(); x.Span(" of "); x.TotalPages(); });
            });

            // ── Page 4: Amortization ─────────────────────────────────────
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Text("Amortization Overview").FontSize(16).Bold().FontColor("#FF6600");

                page.Content().PaddingTop(20).Column(col =>
                {
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(c =>
                        {
                            c.ConstantColumn(60);
                            c.RelativeColumn();
                            c.RelativeColumn();
                        });

                        table.Header(h =>
                        {
                            h.Cell().Text("Year").Bold();
                            h.Cell().Text("Cumulative Savings (€)").Bold();
                            h.Cell().Text("System Cost (€)").Bold();
                        });

                        foreach (var a in data.AmortizationData)
                        {
                            table.Cell().Text(a.Year.ToString());
                            table.Cell().Text($"{a.CumulativeSavings:N0}");
                            table.Cell().Text($"{a.CumulativeCost:N0}");
                        }
                    });
                });

                page.Footer().AlignRight()
                    .Text(x => { x.Span("Page "); x.CurrentPageNumber(); x.Span(" of "); x.TotalPages(); });
            });

        }).GeneratePdf();
    }

    private static void AddMetricRow(TableDescriptor table, string label, string value)
    {
        table.Cell().Padding(4).Text(label).FontColor("#555555");
        table.Cell().Padding(4).Text(value).Bold();
    }
}