server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA routing - all unknow paths serve index.html so Angular router takes over
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets aggressively  - hashed filenames change on rebuild
    location ~* \.(js|css|png|jpg|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}